import { mkdirSync } from "node:fs";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { createClient, type Client } from "@libsql/client";
import { drizzle, type LibSQLDatabase } from "drizzle-orm/libsql";
import { migrate } from "drizzle-orm/libsql/migrator";

import { config, fileUrlToPathSafe } from "../config.ts";
import * as schema from "./schema.ts";

export type Db = LibSQLDatabase<typeof schema>;
export type { Client };

function prepareFileUrl(url: string): void {
  if (!url.startsWith("file:")) return;
  mkdirSync(dirname(fileUrlToPathSafe(url)), { recursive: true });
}

export async function createDb(databaseUrl: string = config.databaseUrl): Promise<{
  client: Client;
  db: Db;
}> {
  prepareFileUrl(databaseUrl);
  const client = createClient({ url: databaseUrl });
  // WAL + FK are the frozen posture (D16/D20). Awaited before any DDL/DML so
  // pragmas are guaranteed active (retro-fix: fire-and-forget `void` was a race).
  await client.execute("PRAGMA journal_mode = WAL");
  await client.execute("PRAGMA foreign_keys = ON");
  const db = drizzle(client, { schema });
  return { client, db };
}

/** D18: migrations generated by drizzle-kit from schema.ts (single source).
 *  `../../drizzle` resolves correctly from both src/ (node --watch) and dist/ (build). */
export async function ensureSchema(db: Db): Promise<void> {
  await migrate(db, {
    migrationsFolder: fileURLToPath(new URL("../../drizzle", import.meta.url)),
  });
}
